<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2026.1</Version>
        <HsnSoftFrameworkVersion>2026.10.5</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>10.0.4</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>10.0.4</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>